### ISSUE TITLE
Unable to Sign in using the api via my Gmail credentials

### ISSUE THREAD

**Issue by rahuja23** [sokovnich/hotjar-api#2]
Hi  Sokovnich! Firstly pretty awesome code and thanks a lot for publishing it. I just have a question, I don't really have specific hotjar credentials I usually sign up using my gmail credentials. Is there any way you can help me do that via the API?

Thanks in advance for your time.

**Comment by sokovnich** [comment]
Hi!
You can try to get your hotjar account credentials via password resetting form
even if you signed up via Google SSO.
It should help. Otherwise you need to implement SSO authorization support by yourself.
